/**
 * THE BREW HAVEN — products.js
 * Central product data store used across all pages
 */

const PRODUCTS = [
    {
        id: 'coorg-light-roast',
        name: 'Single Origin Coorg Light Roast',
        shortName: 'Coorg Light Roast',
        category: 'light-roast',
        price: 649,
        weight: '250g',
        image: 'assets/images/prod-coorg-light.png',
        tastingNotes: ['Citrus', 'Jasmine', 'Honey'],
        origin: 'Kodagu, Karnataka',
        elevation: '1,200m',
        process: 'Washed',
        roast: 'Light',
        farm: 'Devagiri Estate',
        description: 'Grown at 1,200m altitude in Kodagu\'s misty, pepper-vine-shaded estates. Handpicked during peak harvest and sun-dried on raised beds. The high altitude and cool nights amplify inherent sweetness — producing a clean, bright cup with floral delicacy.',
        longDesc: 'Every harvest at Devagiri Estate begins before sunrise. The pickers — many of them third-generation coffee farmers — move methodically through the shaded groves, selecting only the ripest red cherries by hand. The result is a coffee of extraordinary clarity. Washed and dried on African-style raised beds for 18–21 days, the Coorg Light Roast retains its inherent sweetness while developing bright acidity that coffee connoisseurs prize.',
        badge: 'Bestseller',
        brewMethods: ['Pour Over', 'AeroPress', 'Filter Coffee'],
        available: true,
        featured: true,
    },
    {
        id: 'dark-reserve-blend',
        name: 'Dark Roast Reserve Blend',
        shortName: 'Dark Reserve Blend',
        category: 'dark-roast',
        price: 749,
        weight: '250g',
        image: 'assets/images/prod-dark-reserve.png',
        tastingNotes: ['Dark Chocolate', 'Molasses', 'Oak'],
        origin: 'Chikmagalur, Karnataka',
        elevation: '1,800m',
        process: 'Natural',
        roast: 'Dark',
        farm: 'Mullayanagiri Hills Estate',
        description: 'Sourced from the Bababudangiri hills — where Indian coffee history began. Slow-roasted in small batches to develop deep, resonant complexity.',
        longDesc: 'The Mullayanagiri Hills rise to nearly 1,900 metres — among the highest peaks in Southern India. The altitude, the volcanic soil, and the cool, cloud-covered climate create ideal conditions for slow, measured cherry development. Our Dark Reserve undergoes a 12-day natural process before being slow-roasted to bring out its deep, resonant character. This is a coffee of authority and depth — built for espresso lovers, moka pot devotees, and anyone who believes that a coffee should have something to say.',
        badge: 'New Arrival',
        brewMethods: ['Moka Pot', 'French Press', 'Espresso'],
        available: true,
        featured: true,
    },
    {
        id: 'cold-brew-concentrate',
        name: 'Cold Brew Concentrate',
        shortName: 'Cold Brew Concentrate',
        category: 'cold-brew',
        price: 549,
        weight: '500ml',
        image: 'assets/images/prod-cold-brew.png',
        tastingNotes: ['Caramel', 'Stone Fruit', 'Cream'],
        origin: 'Dual Origin Blend',
        elevation: 'Mixed',
        process: 'Cold Steeped 18hrs',
        roast: 'Medium',
        farm: 'Coorg + Chikmagalur',
        description: 'Steeped for 18 hours using a proprietary blend of Coorg and Chikmagalur beans. Low acid, naturally sweet, engineered for summer.',
        longDesc: 'Our cold brew is steeped for 18 hours at a controlled temperature of 4°C using filtered water. The process draws out natural sweetness while suppressing the acids that make hot-brewed coffee difficult on a warm day. The result is a silky, deeply complex concentrate that dilutes 1:4 with water or milk. Shake well, pour over ice, and experience what summer in Coorg tastes like.',
        badge: 'Limited Edition',
        brewMethods: ['Cold Brew', 'Iced Latte'],
        available: true,
        featured: true,
    },
    {
        id: 'honey-process',
        name: 'Chikmagalur Honey Process',
        shortName: 'Honey Process',
        category: 'light-roast',
        price: 849,
        weight: '200g',
        image: 'assets/images/prod-honey-process.png',
        tastingNotes: ['Wildflower Honey', 'Peach', 'Brown Sugar'],
        origin: 'Chikmagalur, Karnataka',
        elevation: '1,500m',
        process: 'Honey',
        roast: 'Medium-Light',
        farm: 'Kemmanagundi Estate',
        description: 'A rare honey-processed lot from our Kemmanagundi partners. The mucilage is left intact during drying, giving this coffee its signature sweetness.',
        longDesc: 'Honey processing is a delicate middle path between washed and natural. The coffee cherry skin is removed, but a precise amount of the sticky mucilage — naturally rich in sugars — is left on the bean during drying. At Kemmanagundi, our farm partners dry the beans on raised beds for up to 21 days, turning them by hand every few hours. The result is a coffee of extraordinary sweetness that feels almost dessert-like in the cup.',
        badge: 'Rare Find',
        brewMethods: ['Pour Over', 'AeroPress', 'Siphon'],
        available: true,
        featured: false,
    },
    {
        id: 'espresso-blend',
        name: 'The Brew Haven Espresso',
        shortName: 'Espresso Blend',
        category: 'dark-roast',
        price: 699,
        weight: '250g',
        image: 'assets/images/prod-espresso.png',
        tastingNotes: ['Dark Caramel', 'Hazelnut', 'Cocoa'],
        origin: 'Coorg + Chikmagalur Blend',
        elevation: 'Mixed',
        process: 'Natural + Washed Blend',
        roast: 'Dark',
        farm: 'Multi-Farm',
        description: 'Our signature espresso blend — engineered for rich crema and a long, lingering finish. Works perfectly as an espresso or a milk-based drink.',
        longDesc: 'Building the perfect espresso is an act of precision. Our espresso blend combines 60% Arabica from Coorg with 40% Robusta from the Chikmagalur lowlands — creating a balance of sweetness and body that blooms under pressure. The Robusta provides structural strength and crema; the Arabica provides nuance and aroma. In a double espresso, this blend delivers 28 seconds of what we consider the ideal extraction.',
        badge: null,
        brewMethods: ['Espresso', 'Moka Pot', 'Americano'],
        available: true,
        featured: false,
    },
    {
        id: 'filter-coffee-blend',
        name: 'South Indian Filter Blend',
        shortName: 'Filter Blend',
        category: 'dark-roast',
        price: 499,
        weight: '250g',
        image: 'assets/images/prod-filter.png',
        tastingNotes: ['Chicory', 'Dark Toffee', 'Smoke'],
        origin: 'Coorg, Karnataka',
        elevation: '900m',
        process: 'Washed + 10% Chicory',
        roast: 'Dark',
        farm: 'Madikeri Collective',
        description: 'Our homage to the morning ritual. A classic South Indian filter blend with 10% chicory roasted to deep, comforting darkness.',
        longDesc: 'There is no more intimate morning ritual in South India than the filter coffee. The slow drip of the decoction through the brass filter, the billow of steam as hot milk is added, the satisfied sound of it being poured back and forth between tumblers to cool and foam — this is what we grew up with. Our Filter Blend carries that tradition. Made with 90% Coorg Arabica and 10% chicory, roasted dark and ground specifically for traditional brass filters.',
        badge: 'Heritage',
        brewMethods: ['Filter Coffee', 'Percolator'],
        available: true,
        featured: false,
    },
    {
        id: 'pour-over-kit',
        name: 'Pour Over Starter Kit',
        shortName: 'Pour Over Kit',
        category: 'equipment',
        price: 1849,
        weight: 'Kit',
        image: 'assets/images/prod-pour-over-kit.png',
        tastingNotes: ['Clarity', 'Precision', 'Ritual'],
        origin: 'Curated by The Brew Haven',
        elevation: '—',
        process: '—',
        roast: '—',
        farm: 'Includes Coorg Light Roast (100g)',
        description: 'Everything you need to start brewing perfectly at home: Chemex, gooseneck kettle, filter papers, and a 100g bag of our Coorg Light Roast.',
        longDesc: 'This kit contains: 1× 3-cup Chemex carafe with wooden handle; 1× 100g bag of our single-origin Coorg Light Roast (pre-ground for pour over); 1× pack of 30 Chemex filter papers; 1× brew ratio guide card; 1× hand-illustrated brewing instruction booklet from The Brew Haven. The perfect first step toward understanding coffee as a craft.',
        badge: 'Bundle',
        brewMethods: ['Pour Over'],
        available: true,
        featured: false,
    },
    {
        id: 'subscription-box',
        name: 'The Connoisseur\'s Box',
        shortName: 'Subscription Box',
        category: 'bundles',
        price: 1299,
        weight: 'Monthly',
        image: 'assets/images/prod-subscription.png',
        tastingNotes: ['Discovery', 'Variety', 'Surprise'],
        origin: 'Rotating Origins',
        elevation: 'Varies',
        process: 'Varies',
        roast: 'Your Choice',
        farm: 'Multi-Farm Seasonal',
        description: 'A monthly curation of two premium bags (150g each), tasting notes, brewing guide, and a seasonal exclusive. Cancel anytime.',
        longDesc: 'Every month, our sourcing team selects the two most exciting lots from our farm partners across Coorg and Chikmagalur. You receive: 2× 150g bags (your choice of roast profile); handwritten tasting notes from our head roaster; a seasonal brewing guide with the featured method; an exclusive member offer. Each box is a new chapter in the story of Indian specialty coffee. No contracts. Cancel whenever you like.',
        badge: 'Most Popular',
        brewMethods: ['All Methods'],
        available: true,
        featured: true,
    },
];

// Export for use in all pages
if (typeof module !== 'undefined') module.exports = { PRODUCTS };
